baseURL = "https://hugoshop.netlify.com"
languageCode = "en-us"
title = "Awesome Lighting Inc."
theme = "myshop"
#theme = "hugo-shopping-product-catalogue-simple"
#themesDir = "../.."
[Params]
description = ""
